name: Build and Push Docker Image

on:
  push:
    branches:
      - nodejs

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract version from Dockerfile
      id: extract_version
      run: |
        APP_VERSION=$(grep 'ARG APP_VERSION=' Dockerfile | cut -d '=' -f2)
        echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/test-nodejs:${{ env.APP_VERSION }}
