name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract version from Dockerfile
      id: extract_version
      run: |
        VERSION=$(grep 'ARG VERSION=' Dockerfile | cut -d '=' -f2)
        if [ -z "$VERSION" ]; then
          echo "VERSION not found in Dockerfile"
          exit 1
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/flask-test:${{ env.VERSION }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
